import React, { useEffect, useState } from "react";
import axios from "axios";
import "../../style/Report.css";

const AdminSavedReports = () => {
  const token = localStorage.getItem("token");

  const [reports, setReports] = useState([]);
  const [selectedReport, setSelectedReport] = useState(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    fetchSavedReports();
  }, []);

  const fetchSavedReports = async () => {
    try {
      setLoading(true);
      const res = await axios.get("http://https://employee-analysis-system-1.onrender.com//api/reports/saved", {
        headers: { Authorization: `Bearer ${token}` },
      });
      setReports(res.data || []);
    } catch (error) {
      console.error("Fetch saved reports error:", error);
      alert(error.response?.data?.message || "Failed to fetch saved reports");
    } finally {
      setLoading(false);
    }
  };

  const openReport = async (id) => {
    try {
      setLoading(true);
      const res = await axios.get(`http://https://employee-analysis-system-1.onrender.com//api/reports/saved/${id}`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      setSelectedReport(res.data);
    } catch (error) {
      console.error("Open report error:", error);
      alert(error.response?.data?.message || "Failed to open report");
    } finally {
      setLoading(false);
    }
  };

  const handleExportPDF = async (id, reportType) => {
    try {
      const res = await axios.get(
        `http://https://employee-analysis-system-1.onrender.com//api/reports/export-pdf/${id}`,
        {
          headers: { Authorization: `Bearer ${token}` },
          responseType: "blob",
        }
      );

      const url = window.URL.createObjectURL(new Blob([res.data]));
      const link = document.createElement("a");
      link.href = url;
      link.setAttribute("download", `${reportType}.pdf`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error("PDF export error:", error);
      alert("PDF export failed");
    }
  };

  const handleExportExcel = async (id, reportType) => {
    try {
      const res = await axios.get(
        `http://https://employee-analysis-system-1.onrender.com//api/reports/export-excel/${id}`,
        {
          headers: { Authorization: `Bearer ${token}` },
          responseType: "blob",
        }
      );

      const url = window.URL.createObjectURL(new Blob([res.data]));
      const link = document.createElement("a");
      link.href = url;
      link.setAttribute("download", `${reportType}.xlsx`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Excel export error:", error);
      alert("Excel export failed");
    }
  };

  return (
    <div className="report-page">
      <h2 className="report-page-title">Saved Reports</h2>

      {!selectedReport ? (
        <div className="report-table-card">
          <div className="report-table-header">
            <h3>HR Generated Reports</h3>
          </div>

          <div className="report-table-wrapper">
            <table className="report-table">
              <thead>
                <tr>
                  <th>Report Type</th>
                  <th>Generated By</th>
                  <th>Generated At</th>
                  <th>View</th>
                  <th>PDF</th>
                  <th>Excel</th>
                </tr>
              </thead>
              <tbody>
                {reports.length > 0 ? (
                  reports.map((item) => (
                    <tr key={item._id}>
                      <td>{item.reportType}</td>
                      <td>{item.generatedBy?.name || "-"}</td>
                      <td>{new Date(item.generatedAt).toLocaleString()}</td>
                      <td>
                        <button
                          className="generate-btn"
                          onClick={() => openReport(item._id)}
                        >
                          View
                        </button>
                      </td>
                      <td>
                        <button
                          className="pdf-btn"
                          onClick={() => handleExportPDF(item._id, item.reportType)}
                        >
                          PDF
                        </button>
                      </td>
                      <td>
                        <button
                          className="excel-btn"
                          onClick={() => handleExportExcel(item._id, item.reportType)}
                        >
                          Excel
                        </button>
                      </td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td colSpan="6" style={{ textAlign: "center", padding: "20px" }}>
                      {loading ? "Loading..." : "No saved reports available"}
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      ) : (
        <>
          <div className="report-action-row" style={{ marginBottom: "16px" }}>
            <button className="reset-btn" onClick={() => setSelectedReport(null)}>
              Back to Saved Reports
            </button>
            <button
              className="pdf-btn"
              onClick={() =>
                handleExportPDF(selectedReport._id, selectedReport.reportType)
              }
            >
              Export PDF
            </button>
            <button
              className="excel-btn"
              onClick={() =>
                handleExportExcel(selectedReport._id, selectedReport.reportType)
              }
            >
              Export Excel
            </button>
          </div>

          <div className="report-summary-grid">
            <div className="summary-card blue">
              <h4>Total Records</h4>
              <p>{selectedReport.summary?.totalRecords || 0}</p>
            </div>
            <div className="summary-card green">
              <h4>Total Active</h4>
              <p>{selectedReport.summary?.totalActive || 0}</p>
            </div>
            <div className="summary-card orange">
              <h4>Pending / Late</h4>
              <p>{selectedReport.summary?.totalPendingLate || 0}</p>
            </div>
          </div>

          <div className="report-table-card">
            <div className="report-table-header">
              <h3>{selectedReport.reportType}</h3>
            </div>

            <div className="report-table-wrapper">
              <table className="report-table">
                <thead>
                  <tr>
                    <th>Employee</th>
                    <th>Department</th>
                    <th>Date</th>
                    <th>Status</th>
                    <th>Details</th>
                  </tr>
                </thead>
                <tbody>
                  {selectedReport.rows?.length > 0 ? (
                    selectedReport.rows.map((row, index) => (
                      <tr key={index}>
                        <td>{row.employeeName}</td>
                        <td>{row.department}</td>
                        <td>{row.date}</td>
                        <td>{row.status}</td>
                        <td>{row.details}</td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colSpan="5" style={{ textAlign: "center", padding: "20px" }}>
                        No report data available
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </>
      )}
    </div>
  );
};

export default AdminSavedReports;